---
title: "bwca_map"
author: "Matt Ploenzke"
date: "1/1/2020"
output: html_document
---

Load packages.
```{r}
library(tidyverse)
library(osmdata)
library(ggrepel)
```

Pull known BWCA lake names.
```{r, eval=FALSE}
library(rvest)
url_site <- html('https://www.paddleplanner.com/tools/lakedatabase.aspx?area=1')
all_bwca_lakes <- url_site %>%
  html_nodes("td:nth-child(1) a") %>%
  html_text()
```

Check available features.
```{r, eval=FALSE}
available_features()
available_tags("highway")
```

Pull lakes data.
```{r}
locations <- c('Cook County, Minnesota, United States',
               'Lake County, Minnesota, United States',
               'Saint Louis County, Minnesota, United States')

lakes_data <- lapply(locations, function(location) {
  getbb(location, key='natural') %>%
    opq()  %>%
    add_osm_feature(key='natural',value='water') %>%
    osmdata_sf()
})
```

Pull rivers.
```{r}
rivers <- lapply(locations, function(location) {
  getbb(location)%>%
  opq()%>%
  add_osm_feature(key = "waterway") %>%
  osmdata_sf()
})
```

Pull BWCA border.
```{r}
bwca <- opq_osm_id(id='1070324', type='relation') %>% 
  opq_string() %>%
  osmdata_sf() 
```

Grab international border
```{r}
canada_border <- opq_osm_id(id='1428125', type='relation') %>% 
  opq_string() %>%
  osmdata_sf() 
```

Grab roads.
```{r}
primary_streets <- lapply(locations, function(location) {
  getbb(location) %>%
  opq()%>%
  add_osm_feature(key = "highway", 
                  value = c("motorway", "trunk","primary")) %>%
  osmdata_sf()
})
secondary_streets <- lapply(locations, function(location) {
  getbb(location) %>%
  opq()%>%
  add_osm_feature(key = "highway", 
                  value = c("secondary","tertiary")) %>%
  osmdata_sf()
})
residential_streets <- lapply(locations, function(location) {
  getbb(location) %>%
  opq()%>%
  add_osm_feature(key = "highway", 
                  value = c("residential")) %>%
  osmdata_sf()
})
```

Trim roads.
```{r}
mnbb <- getbb('Minnesota',format_out='polygon')
primary_streets <- lapply(primary_streets, function(location) {trim_osmdata(location,mnbb, exclude=FALSE)})
secondary_streets <- lapply(secondary_streets, function(location) {trim_osmdata(location,mnbb, exclude=FALSE)})
residential_streets <- lapply(residential_streets, function(location) {trim_osmdata(location,mnbb, exclude=FALSE)})
```

Add cities of interest.
```{r}
ely <- opq_osm_id(id='137427', type='relation') %>% 
  opq_string() %>%
  osmdata_sf() 
grandmarais <- opq_osm_id(id='137679', type='relation') %>% 
  opq_string() %>%
  osmdata_sf() 
tower <- opq_osm_id(id='136850', type='relation') %>% 
  opq_string() %>%
  osmdata_sf() 
babbitt <- opq_osm_id(id='136657', type='relation') %>% 
  opq_string() %>%
  osmdata_sf() 
```

Grab background from google maps API.
```{r, eval=FALSE}
library(ggmap)
ggmap_show_api_key()
base_map <- get_map(location = c(lon=-91.5,lat=48),maptype = "satellite", zoom=8)
ggmap(base_map)
ggmap_hide_api_key()
```

Plot it.
```{r}
p <- ggplot()
for (lake in 1:length(lakes_data)) {
  p <- p +
    geom_sf(data=lakes_data[[lake]]$osm_multipolygons,
            inherit.aes = FALSE,
            color = "#002c57",
            fill="#004a92",
            size = .5,
            alpha = 1) + 
    geom_sf(data=lakes_data[[lake]]$osm_polygons,
            inherit.aes = FALSE,
            color = "#002c57",
            fill="#004a92",
            size = .5,
            alpha = 1) +
    geom_sf(data = rivers[[lake]]$osm_lines,
            inherit.aes = FALSE,
            color = "#004a92",
            fill="#004a92",
            size = .2,
            alpha = 1) +
    geom_sf(data=primary_streets[[lake]]$osm_lines,
            inherit.aes = FALSE,
            color = "#FF6300",
            size = .3,
            alpha = .8) +
     geom_sf(data=secondary_streets[[lake]]$osm_lines,
            inherit.aes = FALSE,
            color = "#FF6300",
            size = .2,
            alpha = .8) +
    geom_sf(data=residential_streets[[lake]]$osm_lines,
            inherit.aes = FALSE,
            color = "#FF8232",
            size = .1,
            alpha = .4)
}
p <- p +
  geom_sf(data = bwca$osm_multipolygons,
          inherit.aes = FALSE,
          color = "forestgreen",
          fill=NA,
          size = .8,
          alpha = 1) + 
  geom_sf(data = canada_border$osm_multipolygons,
          inherit.aes = FALSE,
          lty = 'dotted',
          color = "grey50",
          fill=NA,
          size = .8,
          alpha = 1) +
  geom_sf(data = ely$osm_multipolygons,
          inherit.aes = FALSE,
          fill = "#FF6300",
          color=NA,
          size = .4,
          alpha = .4) +
  geom_sf(data = grandmarais$osm_multipolygons,
          inherit.aes = FALSE,
          fill = "#FF6300",
          color=NA,
          size = .4,
          alpha = .4) +
  geom_sf(data = tower$osm_multipolygons,
          inherit.aes = FALSE,
          fill = "#FF6300",
          color=NA,
          size = .4,
          alpha = .4) +
    coord_sf(xlim = c(-92.5, -90), 
           ylim = c(47.7, 48.4),
           expand = FALSE) +
  annotate("rect", xmin = -91.75, xmax = -90.75, ymin = 48.325, ymax=48.375, color='cornsilk', fill='#005000') +
  annotate("text", x = -91.25, y = 48.35, label = "Boundary Waters Canoe Area Wilderness", size=8, 
           color='cornsilk', family='Times',fontface='italic') +
  annotate("text", x = -92.325, y = 47.71, label = "Data from: Open Street Maps", size=4, 
           color='cornsilk', family='Times',fontface='italic') +
  annotate("text", x = -90.175, y = 47.71, label = "Created by: Matt Ploenzke", size=4, 
           color='cornsilk', family='Times',fontface='italic') +
  geom_segment(aes(x=-90.19, xend = -90.19, y=48.25, yend = 48.35), 
               arrow = arrow(angle=35, length = unit(0.2,"cm"), type='closed', ends='last'), 
               color='grey70') +
  geom_segment(aes(x=-90.19, xend=-90.215, y=48.25,yend=48.235),color='grey70') +
  geom_segment(aes(x=-90.19, xend=-90.165, y=48.25,yend=48.235),color='grey70') +
  geom_segment(aes(x=-90.19, xend=-90.215, y=48.265,yend=48.25),color='grey70') +
  geom_segment(aes(x=-90.19, xend=-90.165, y=48.265,yend=48.25),color='grey70') +
  geom_segment(aes(x=-90.125, xend = -90.25, y=48.3, yend = 48.3), 
               arrow = arrow(angle=35, length = unit(0.2,"cm"), type='closed', ends='first'), 
               color='grey70') +
  geom_segment(aes(x=-90.275, xend=-90.25, y=48.285,yend=48.3),color='grey70') +
  geom_segment(aes(x=-90.275, xend=-90.25, y=48.315,yend=48.3),color='grey70') +
  geom_segment(aes(x=-90.25, xend=-90.225, y=48.285,yend=48.3),color='grey70') +
  geom_segment(aes(x=-90.25, xend=-90.225, y=48.315,yend=48.3),color='grey70') +
  annotate("text", x = -90.1875, y = 48.375, label = "N", size=6, 
           color='grey70', family='Times',fontface='italic') +
  annotate("text", x = -90.1, y = 48.3, label = "E", size=6, 
           color='grey70', family='Times',fontface='italic') +
  geom_point(aes(x=-92.099086, y=48.12303), size=2, color='red') + 
  geom_label_repel(aes(x=-92.099086, y=48.12303, label='16'), size=3, box.padding=.5,min.segment.length=0,
           color='red', family='Times',fontface='italic',fill="#002900") + 
  geom_point(aes(x=-90.644793, y=47.92606), size=2, color='red') + 
  geom_label_repel(aes(x=-90.644793, y=47.92606, label='41'), size=3, box.padding=.5,min.segment.length=0,
           color='red', family='Times',fontface='italic',fill="#002900") + 
  geom_point(aes(x=-90.885782,y=47.86987), size=2, color='red') + 
  geom_label_repel(aes(x=-90.885782,y=47.86987, label='38'), size=3, box.padding=.5,min.segment.length=0,
           color='red', family='Times',fontface='italic',fill="#002900") + 
  geom_point(aes(x=-90.532647,y=48.04399), size=2, color='red') + 
  geom_label_repel(aes(x=-90.532647,y=48.04399, label='48'), size=3, box.padding=.5,min.segment.length=0,
           color='red', family='Times',fontface='italic',fill="#002900") + 
    geom_point(aes(x=-91.499687,y=47.9877), size=2, color='red') + 
  geom_label_repel(aes(x=-91.499687,y=47.9877, label='25'), size=3, box.padding=.5,min.segment.length=0,
           color='red', family='Times',fontface='italic',fill="#002900") + 
  theme_void() +
  theme(panel.background = element_rect(fill = "#002900",colour = "#002900"))
ggsave('map.png',width=16,height=6.705, units='in')
```

remove roads in canada
add entry points
